### DO NOT CHANGE - GitHub Pages will force these defaults ###
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
### END forced defaults - config will be honored if valid  ###
  input: GFM
  hard_wrap: false
repository: oac4/altc
gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
sass:
  sass_dir: _sass
  style: compressed
timezone: America/New_York
encoding: utf-8
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
### Custom config - these are used for display on the site ###
title: Conclave 2017
event_start: May 19, 2017 18:00:00
date_range: May 19-21, 2017

